Repository chipsalliance/caliptra-sw, pull requests merged in 2023-03, with the labels that each got.

#8 Add additional details to FMC doc
  fmc/README.md
  fmc/doc/diagrams/Caliptra_FMC_Boot_Sequence.svg
Labels: documentation

#123 [fix] [FHT] rt_fw_load_addr_idx loaded with rt_entry_point_idx
  rom/dev/src/fht.rs
Labels: bug

#118 Add panic detection tests to FMC and RT crates.
  fmc/src/main.rs
  fmc/tests/test_panic_missing.rs
  runtime/src/main.rs
  runtime/tests/test_panic_missing.rs
Labels: enhancement
