Repository chipsalliance/caliptra-sw, pull requests merged in 2024-11, with the labels that each got.

#1760 [doc] Updating the Production Debug unlock process + FUSE_IDEVID_CERT_ATTR fuse format
  rom/dev/README.md
Labels: Caliptra v2.0

#1694 [feat] Image generator and verifier updates for Caliptra 2.0 FW ECC + LMS image
  Cargo.lock
  builder/src/lib.rs
  common/src/verifier.rs
  drivers/src/fuse_bank.rs
  drivers/src/memory_layout.rs
  drivers/src/pcr_log.rs
  error/src/lib.rs
  fmc/tests/fmc_integration_tests/test_rtalias.rs
  image/app/src/create/config.rs
  image/app/src/create/mod.rs
  image/app/src/main.rs
  image/elf/src/lib.rs
  image/fake-keys/src/lib.rs
  image/gen/src/generator.rs
  image/gen/src/lib.rs
  image/serde/Cargo.toml
  image/serde/src/lib.rs
  image/types/src/lib.rs
  image/verify/src/lib.rs
  image/verify/src/verifier.rs
  libcaliptra/examples/generic/test.c
  rom/dev/Makefile
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/src/flow/cold_reset/fw_processor.rs
  rom/dev/src/flow/fake.rs
  rom/dev/src/pcr.rs
  rom/dev/tests/rom_integration_tests/test_fake_rom.rs
  rom/dev/tests/rom_integration_tests/test_fmcalias_derivation.rs
  rom/dev/tests/rom_integration_tests/test_image_validation.rs
  rom/dev/tests/rom_integration_tests/test_update_reset.rs
  rom/dev/tests/rom_integration_tests/test_warm_reset.rs
  rom/dev/tools/test-rt/src/main.rs
  runtime/src/set_auth_manifest.rs
  runtime/tests/runtime_integration_tests/test_pauser_privilege_levels.rs
  runtime/tests/runtime_integration_tests/test_warm_reset.rs
  test/tests/caliptra_integration_tests/fake_collateral_boot_test.rs
  test/tests/caliptra_integration_tests/jtag_test.rs
  test/tests/caliptra_integration_tests/smoke_test.rs
  test/tests/caliptra_integration_tests/warm_reset.rs
  test/tests/fips_test_suite/fw_load.rs
Labels: Caliptra v2.0

#1763 Adding the stash measurement functionality to AuthorizeAndStashCmd
  error/src/lib.rs
  runtime/src/authorize_and_stash.rs
  runtime/src/stash_measurement.rs
Labels: Caliptra v1.2

#1747 [feat] Add HMAC512 mode to Emulator
  drivers/src/hmac384.rs
  sw-emulator/lib/crypto/src/hmac512.rs
  sw-emulator/lib/crypto/src/lib.rs
  sw-emulator/lib/periph/src/hmac.rs
  sw-emulator/lib/periph/src/lib.rs
  sw-emulator/lib/periph/src/root_bus.rs
Labels: Caliptra v2.0

#1768 [update] Make image verification with PQC algorithms mandatory
  common/src/verifier.rs
  drivers/src/fuse_bank.rs
  drivers/src/lib.rs
  image/verify/fuzz/src/fuzz_target_common.rs
  image/verify/src/lib.rs
  image/verify/src/verifier.rs
  rom/dev/doc/test-coverage/test-coverage.md
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/src/flow/cold_reset/fw_processor.rs
  rom/dev/src/flow/fake.rs
  rom/dev/src/pcr.rs
  rom/dev/tests/rom_integration_tests/test_fmcalias_derivation.rs
  rom/dev/tests/rom_integration_tests/test_image_validation.rs
  runtime/src/authorize_and_stash.rs
  runtime/src/set_auth_manifest.rs
  test/tests/caliptra_integration_tests/smoke_test.rs
Labels: Caliptra v2.0

#1725 Cert tweaks to names and TCB info
  FROZEN_IMAGES.sha384sum
  fmc/tests/fmc_integration_tests/test_rtalias.rs
  libcaliptra/examples/generic/idev_csr_array.h
  rom/dev/build.rs
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/tests/rom_integration_tests/test_fmcalias_derivation.rs
  runtime/src/dpe_platform.rs
  test/src/x509.rs
  test/tests/caliptra_integration_tests/smoke_test.rs
  test/tests/caliptra_integration_tests/smoke_testdata/fmc_alias_cert_redacted.der
  test/tests/caliptra_integration_tests/smoke_testdata/fmc_alias_cert_redacted.txt
  test/tests/caliptra_integration_tests/smoke_testdata/idevid_csr.der
  test/tests/caliptra_integration_tests/smoke_testdata/idevid_csr.txt
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.der
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.txt
  test/tests/caliptra_integration_tests/smoke_testdata/rt_alias_cert_redacted.der
  test/tests/caliptra_integration_tests/smoke_testdata/rt_alias_cert_redacted.txt
  x509/build/build.rs
  x509/build/cert.rs
  x509/build/fmc_alias_cert_tbs.rs
  x509/build/init_dev_id_csr_tbs.rs
  x509/build/local_dev_id_cert_tbs.rs
  x509/build/rt_alias_cert_tbs.rs
  x509/build/x509.rs
Labels: ROM, FMC

#1714 cfi: Simpler launder implementation for common types
  Cargo.lock
  FROZEN_IMAGES.sha384sum
  cfi/derive/src/cfi_asm_test.rs
  cfi/derive/src/lib.rs
  cfi/lib/src/cfi.rs
  drivers/src/array.rs
  drivers/src/fuse_bank.rs
  drivers/src/soc_ifc.rs
  fmc/src/flow/rt_alias.rs
  image/types/Cargo.toml
  image/verify/src/verifier.rs
  lms-types/Cargo.toml
  lms-types/src/lib.rs
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/src/flow/cold_reset/idev_id.rs
  rom/dev/src/flow/cold_reset/ldev_id.rs
Labels: Caliptra v1.2

#1734 [feat] x509 MLDSA Certificate and CSR
  Cargo.lock
  rom/dev/src/flow/cold_reset/idev_id.rs
  rom/dev/tools/test-fmc/src/fmc.ld
  rom/dev/tools/test-fmc/src/main.rs
  rom/dev/tools/test-rt/Cargo.toml
  rom/dev/tools/test-rt/build.rs
  rom/dev/tools/test-rt/src/main.rs
  rom/dev/tools/test-rt/src/rt.ld
  x509/src/cert_bldr.rs
  x509/src/der_helper.rs
  x509/src/lib.rs
Labels: Caliptra v2.0

#1773 [update] Update auth manifest metadata limit to 128
  api/src/mailbox.rs
  auth-manifest/app/src/config.rs
  auth-manifest/gen/src/generator.rs
  auth-manifest/types/src/lib.rs
  drivers/src/lib.rs
  drivers/src/memory_layout.rs
  drivers/src/persistent.rs
  runtime/README.md
  runtime/src/authorize_and_stash.rs
  runtime/src/packet.rs
  runtime/src/set_auth_manifest.rs
  runtime/tests/runtime_integration_tests/test_set_auth_manifest.rs
Labels: Caliptra v1.2

#1733 [feat] ROM IDEVID DICE changes for MLDSA support
  common/src/keyids.rs
  common/src/verifier.rs
  drivers/src/hand_off.rs
  drivers/src/lib.rs
  drivers/src/memory_layout.rs
  drivers/src/persistent.rs
  fmc/tests/fmc_integration_tests/test_rtalias.rs
  image/verify/src/lib.rs
  image/verify/src/verifier.rs
  libcaliptra/examples/generic/idev_csr_array.h
  libcaliptra/src/caliptra_api.c
  rom/dev/src/fht.rs
  rom/dev/src/flow/cold_reset/crypto.rs
  rom/dev/src/flow/cold_reset/dice.rs
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/src/flow/cold_reset/idev_id.rs
  rom/dev/src/flow/cold_reset/ldev_id.rs
  rom/dev/src/flow/cold_reset/mod.rs
  rom/dev/src/flow/fake.rs
  rom/dev/src/rom_env.rs
  runtime/src/info.rs
  test/src/derive.rs
  test/tests/caliptra_integration_tests/fake_collateral_boot_test.rs
  test/tests/caliptra_integration_tests/smoke_test.rs
  test/tests/caliptra_integration_tests/smoke_testdata/idevid_csr.der
  test/tests/caliptra_integration_tests/smoke_testdata/idevid_csr.txt
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.der
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.txt
Labels: Caliptra v2.0

#1732 Add command to retrieve IDevID CSR from persistent storage.
  FROZEN_IMAGES.sha384sum
  api/src/mailbox.rs
  drivers/src/lib.rs
  drivers/src/memory_layout.rs
  drivers/src/persistent.rs
  error/src/lib.rs
  hw-model/src/lib.rs
  rom/dev/README.md
  rom/dev/src/flow/cold_reset/fw_processor.rs
  rom/dev/src/flow/cold_reset/idev_id.rs
  rom/dev/src/flow/cold_reset/x509.rs
  rom/dev/tests/rom_integration_tests/main.rs
  rom/dev/tests/rom_integration_tests/tests_get_idev_csr.rs
  runtime/README.md
  runtime/src/get_idev_csr.rs
  runtime/src/lib.rs
  runtime/tests/runtime_integration_tests/common.rs
  runtime/tests/runtime_integration_tests/main.rs
  runtime/tests/runtime_integration_tests/test_get_idev_csr.rs
Labels: Caliptra v1.2

#1783 inline runtime execute methods
  common/src/fips.rs
  runtime/src/capabilities.rs
  runtime/src/certify_key_extended.rs
  runtime/src/dice.rs
  runtime/src/fips.rs
  runtime/src/info.rs
  runtime/src/invoke_dpe.rs
  runtime/src/pcr.rs
  runtime/src/populate_idev.rs
  runtime/src/subject_alt_name.rs
  runtime/src/tagging.rs
  runtime/src/verify.rs
Labels: Caliptra v1.2

#1780 ci: add dummy workflow for building ROM release from versioned git ref
  .github/workflows/versioned-full-build-test.yml
Labels: Caliptra v1.2

#1781 Don't copy manifest2 onto the stack
  FROZEN_IMAGES.sha384sum
  rom/dev/src/flow/update_reset.rs
Labels: Caliptra v1.2

#1772 Test 'authorize_and_stash' more extensively
  runtime/tests/runtime_integration_tests/test_authorize_and_stash.rs
  runtime/tests/runtime_integration_tests/test_set_auth_manifest.rs
Labels: Caliptra v1.2

#1788 Add GetIdevCsr to libcaliptra.
  libcaliptra/examples/generic/test.c
  libcaliptra/inc/caliptra_api.h
  libcaliptra/inc/caliptra_types.h
  libcaliptra/src/caliptra_api.c
  libcaliptra/src/caliptra_mbox.h
Labels: Caliptra v1.2

#1784 Increase runtime stack size to 64KiB
  drivers/src/memory_layout.rs
Labels: Caliptra v1.2

#1777 [feat] Update HMAC driver for HMAC512 mode
  builder/src/firmware.rs
  common/src/error_handler.rs
  drivers/src/hmac.rs
  drivers/src/hmac384_kdf.rs
  drivers/src/lib.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/doe_tests.rs
  drivers/test-fw/src/bin/hmac_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  error/src/lib.rs
  fmc/src/fmc_env.rs
  kat/src/hmac384kdf_kat.rs
  kat/src/kats_env.rs
  rom/dev/src/flow/cold_reset/crypto.rs
  rom/dev/src/main.rs
  rom/dev/src/rom_env.rs
  runtime/src/disable.rs
  runtime/src/dpe_crypto.rs
  runtime/src/drivers.rs
  runtime/src/fips.rs
  runtime/src/hmac.rs
  test/tests/caliptra_integration_tests/smoke_test.rs
Labels: Caliptra v2.0

#1787 Make `GetIdevCsr` enums / naming consistent with `GetIdevCert` naming.
  api/src/mailbox.rs
  rom/dev/src/flow/cold_reset/fw_processor.rs
  rom/dev/tests/rom_integration_tests/tests_get_idev_csr.rs
  runtime/src/get_idev_csr.rs
  runtime/src/lib.rs
  runtime/tests/runtime_integration_tests/test_get_idev_csr.rs
Labels: Caliptra v1.2

#1771 emulator: Tock registers update
  Cargo.lock
  Cargo.toml
Labels: Caliptra v2.0

#1778 [feat] ML-DSA87 driver
  builder/src/firmware.rs
  drivers/src/lib.rs
  drivers/src/memory_layout.rs
  drivers/src/mldsa87.rs
  drivers/src/persistent.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/mldsa87_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  error/src/lib.rs
  hw/latest/registers/src/i3ccsr.rs
  hw/latest/registers/src/mldsa.rs
  registers/bin/extra-rdl/el2_pic_ctrl.rdl
  registers/bin/generator/src/main.rs
  rom/dev/README.md
  rom/dev/src/flow/cold_reset/crypto.rs
  rom/dev/src/rom_env.rs
  sw-emulator/lib/periph/src/ml_dsa87.rs
  sw-emulator/lib/periph/src/root_bus.rs
  x509/src/cert_bldr.rs
  x509/src/lib.rs
Labels: Caliptra v2.0

#1798 [feat] ROM LDEVID DICE changes for MLDSA support
  rom/dev/src/flow/cold_reset/crypto.rs
  rom/dev/src/flow/cold_reset/dice.rs
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  rom/dev/src/flow/cold_reset/idev_id.rs
  rom/dev/src/flow/cold_reset/ldev_id.rs
  rom/dev/src/flow/cold_reset/mod.rs
  rom/dev/src/flow/cold_reset/x509.rs
  test/src/derive.rs
  test/tests/caliptra_integration_tests/smoke_testdata/fmc_alias_cert_redacted.der
  test/tests/caliptra_integration_tests/smoke_testdata/fmc_alias_cert_redacted.txt
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.der
  test/tests/caliptra_integration_tests/smoke_testdata/ldevid_cert.txt
Labels: Caliptra v2.0

#1799 [feat] ROM ALIAS FMC DICE changes for MLDSA support
  rom/dev/src/flow/cold_reset/fmc_alias.rs
  test/src/derive.rs
Labels: Caliptra v2.0
