Repository chipsalliance/caliptra-sw, pull requests merged in 2025-08, with the labels that each got.

#2352 drivers: Use LEArray types instead of byte slices when possible in AES driver to save code space
  common/src/crypto.rs
  common/src/hmac_cm.rs
  drivers/src/aes.rs
  drivers/src/array.rs
  drivers/src/cmac_kdf.rs
  drivers/src/lib.rs
  drivers/src/persistent.rs
  drivers/test-fw/src/bin/aes_tests.rs
  kat/src/aes256cbc_kat.rs
  kat/src/aes256cmac_kat.rs
  kat/src/aes256ctr_kat.rs
  kat/src/aes256ecb_kat.rs
  kat/src/aes256gcm_kat.rs
  kat/src/cmackdf_kat.rs
  rom/dev/tools/test-fmc/src/main.rs
  runtime/src/cryptographic_mailbox.rs
Labels: Caliptra 2.1

#2346 runtime: Separate SPDM AES enc/dec
  Cargo.lock
  api/src/mailbox.rs
  common/src/lib.rs
  runtime/Cargo.toml
  runtime/README.md
  runtime/src/cryptographic_mailbox.rs
  runtime/src/lib.rs
  runtime/tests/runtime_integration_tests/test_cryptographic_mailbox.rs
Labels: Caliptra v2.0

#2360 feat(MCU staging): Emulate MCU staging area
  .github/workflows/fpga.yml
  builder/src/firmware.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/dma_sha384_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  hw-model/src/model_emulated.rs
  sw-emulator/lib/periph/src/dma/axi_root_bus.rs
Labels: Caliptra v2.0

#2409 fpga: Reset AXI before and after test
  hw-model/src/fpga_regs.rs
  hw-model/src/model_fpga_realtime.rs
  hw-model/src/model_fpga_subsystem.rs
Labels: FPGA, Caliptra v2.0

#2407 Fix flaky build on cold cache (#2404)
  .github/workflows/fpga-subsystem.yml
Labels: FPGA, Caliptra 2.1

#2408 Implement SOC Manifest SVN Verification
  api/src/soc_mgr.rs
  api/types/src/lib.rs
  auth-manifest/app/src/main.rs
  auth-manifest/gen/src/generator.rs
  auth-manifest/gen/src/lib.rs
  auth-manifest/types/src/lib.rs
  drivers/src/fuse_bank.rs
  runtime/src/set_auth_manifest.rs
  runtime/tests/runtime_integration_tests/common.rs
  runtime/tests/runtime_integration_tests/test_authorize_and_stash.rs
  runtime/tests/runtime_integration_tests/test_get_image_info.rs
  runtime/tests/runtime_integration_tests/test_set_auth_manifest.rs
  sw-emulator/lib/periph/src/soc_reg.rs
Labels: Caliptra v2.0
