Repository chipsalliance/caliptra-sw, pull requests merged in 2025-09, with the labels that each got.

#2435 drivers: DMA accelerator has to release unlock itself
  .github/workflows/fpga-subsystem.yml
  .github/workflows/fpga.yml
  builder/src/firmware.rs
  drivers/src/dma.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/dma_sha384_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
Labels: FPGA, Caliptra v2.0

#2455 Use error handler from common crate
  rom/dev/src/main.rs
Labels: Caliptra v2.0

#2457 Disable 3 flaky FPGA tests.
  .github/workflows/fpga.yml
Labels: Caliptra v2.0

#2443 2.1: Add latest changes from main-2.x (September 4, 2025)
  .github/workflows/fpga-image.yml
  .github/workflows/fpga-subsystem.yml
  .github/workflows/fpga.yml
  Cargo.lock
  api/src/soc_mgr.rs
  api/types/src/lib.rs
  auth-manifest/app/src/main.rs
  auth-manifest/gen/src/generator.rs
  auth-manifest/gen/src/lib.rs
  auth-manifest/types/src/lib.rs
  builder/src/firmware.rs
  common/src/error_handler.rs
  drivers/src/dma.rs
  drivers/src/fuse_bank.rs
  drivers/src/mldsa87.rs
  drivers/src/soc_ifc.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/dma_sha384_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  hw-model/src/lib.rs
  hw-model/src/model_fpga_realtime.rs
  hw-model/src/model_fpga_subsystem.rs
  hw-model/src/xi3c/controller.rs
  hw-model/src/xi3c/mod.rs
  hw-model/test-fw/Cargo.toml
  hw/fpga/petalinux_project/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/user_2025-08-26-00-39-00.cfg
  hw/fpga/petalinux_project/project-spec/meta-user/recipes-kernel/linux/linux-xlnx_%.bbappend
  runtime/src/set_auth_manifest.rs
  runtime/tests/runtime_integration_tests/common.rs
  runtime/tests/runtime_integration_tests/test_authorize_and_stash.rs
  runtime/tests/runtime_integration_tests/test_get_image_info.rs
  runtime/tests/runtime_integration_tests/test_set_auth_manifest.rs
  sw-emulator/lib/periph/src/dma/axi_root_bus.rs
  sw-emulator/lib/periph/src/soc_reg.rs
Labels: Caliptra 2.1

#2461 ci: Allow non-linear history in size history job
  ci-tools/size-history/src/git.rs
  ci-tools/size-history/src/main.rs
Labels: Caliptra 2.1

#2468 Fixing PMP tests for FPGA
  .github/workflows/fpga.yml
  rom/dev/tests/rom_integration_tests/test_pmp.rs
  rom/dev/tools/test-fmc/src/main.rs
Labels: Caliptra v2.0

#2306 Pre-conditioned keys
  builder/src/firmware.rs
  drivers/src/lib.rs
  drivers/src/preconditioned_key.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/scripts/vector_gen/src/hmac384_kdf_vector_gen.rs
  drivers/test-fw/scripts/vector_gen/src/hmac384_vector_gen.rs
  drivers/test-fw/scripts/vector_gen/src/main.rs
  drivers/test-fw/scripts/vector_gen/src/preconditioned_key_extract_gen.rs
  drivers/test-fw/scripts/vector_gen/src/utils.rs
  drivers/test-fw/src/bin/preconditioned_keys_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  error/src/lib.rs
Labels: OCP-LOCK

#2412 drivers: AES DMA additional tests
  drivers/src/aes.rs
  drivers/test-fw/src/bin/dma_aes_tests.rs
Labels: FPGA, Caliptra 2.1

#2507 Update README.md with fix for Header info
  rom/dev/README.md
Labels: Caliptra v2.0

#2517 Adds back in ML-KEM drivers and emulator support
  Cargo.lock
  Cargo.toml
  builder/src/firmware.rs
  common/src/error_handler.rs
  drivers/src/array.rs
  drivers/src/key_vault.rs
  drivers/src/kv_access.rs
  drivers/src/lib.rs
  drivers/src/ml_kem.rs
  drivers/test-fw/Cargo.toml
  drivers/test-fw/src/bin/mldsa87_tests.rs
  drivers/test-fw/src/bin/mlkem_tests.rs
  drivers/tests/drivers_integration_tests/main.rs
  error/src/lib.rs
  sw-emulator/lib/periph/Cargo.toml
  sw-emulator/lib/periph/src/abr.rs
  sw-emulator/lib/periph/src/asym_ecc384.rs
  sw-emulator/lib/periph/src/hash_sha512.rs
  sw-emulator/lib/periph/src/helpers.rs
  sw-emulator/lib/periph/src/hmac.rs
  sw-emulator/lib/periph/src/key_vault.rs
  sw-emulator/lib/periph/src/lib.rs
  sw-emulator/lib/periph/src/ml_dsa87.rs
  sw-emulator/lib/periph/src/root_bus.rs
Labels: Caliptra 2.1

#2513 add distpatch and handler for machinetime cmp , also add func to set …
  sw-emulator/lib/bus/src/clock.rs
  sw-emulator/lib/cpu/src/cpu.rs
  sw-emulator/lib/cpu/src/csr_file.rs
Labels: Caliptra v2.0

#2535 hw-model: Make otp_provision and otp_digest modules public for MCU
  hw-model/src/lib.rs
Labels: Caliptra v2.0

#2545 runtime: Avoid immediate save after restore in CM_SHA_UPDATE
  runtime/src/cryptographic_mailbox.rs
  runtime/tests/runtime_integration_tests/test_cryptographic_mailbox.rs
Labels: Caliptra v2.0

#2494 Mark stable keys as FIPS invalid for 2.0 subsystem mode
  Cargo.lock
  api/src/mailbox.rs
  common/src/crypto.rs
  common/src/hmac_cm.rs
  common/src/lib.rs
  drivers/src/aes.rs
  drivers/src/lib.rs
  drivers/src/soc_ifc.rs
  hw-model/Cargo.toml
  hw-model/src/lib.rs
  hw-model/src/model_emulated.rs
  hw-model/src/model_fpga_realtime.rs
  hw-model/src/model_fpga_subsystem.rs
  kat/src/aes256cbc_kat.rs
  kat/src/aes256ctr_kat.rs
  rom/dev/README.md
  rom/dev/src/flow/cold_reset/fw_processor.rs
  rom/dev/tests/rom_integration_tests/test_derive_stable_key.rs
  runtime/README.md
  runtime/src/cryptographic_mailbox.rs
  runtime/tests/runtime_integration_tests/common.rs
  runtime/tests/runtime_integration_tests/test_cryptographic_mailbox.rs
Labels: Caliptra v2.0

#2546 fpga: Support FE programming command test
  .github/workflows/fpga-subsystem.yml
  .github/workflows/fpga.yml
  builder/src/firmware.rs
  builder/src/lib.rs
  hw-model/src/model_fpga_subsystem.rs
  runtime/tests/runtime_integration_tests/common.rs
  runtime/tests/runtime_integration_tests/test_fe_programming.rs
Labels: FPGA, Caliptra v2.0
